#############################################################################
# Makefile for building: arcoder_multimodel
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sun Aug 5 19:03:06 2012
# Project:  ../arcoder_multimodel/arcoder_multimodel.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../arcoder_multimodel/arcoder_multimodel.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W $(DEFINES)
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)    
AR            = ar cqs

SOURCES       = main.cpp \
		BitStream.cpp \
		ArcoderModel.cpp \
		Arcoder.cpp 
OBJECTS       = build/main.o \
		build/BitStream.o \
		build/ArcoderModel.o \
		build/Arcoder.o

####### Build rules

all: build $(OBJECTS)
	$(LINK) $(LFLAGS) -o arcoder $(OBJECTS) $(OBJCOMP) $(LIBS)

build:
	mkdir -p build

####### Compile

build/main.o: main.cpp Arcoder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/BitStream.o: BitStream.cpp BitStream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/BitStream.o BitStream.cpp

build/ArcoderModel.o: ArcoderModel.cpp ArcoderModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/ArcoderModel.o ArcoderModel.cpp

build/Arcoder.o: Arcoder.cpp Arcoder.h ArcoderModel.h BitStream.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/Arcoder.o Arcoder.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

